package pmx

// 标准骨骼名称的日文英文对应表
var BoneNamesTable = map[string]string{
	"センター":   "center",
	"上半身":    "upper body",
	"首":      "neck",
	"頭":      "head",
	"左目":     "eye_L",
	"右目":     "eye_R",
	"ﾈｸﾀｲ１":  "necktie1",
	"ﾈｸﾀｲ２":  "necktie2",
	"ﾈｸﾀｲ３":  "necktie3",
	"下半身":    "lower body",
	"腰飾り":    "waist accessory",
	"左髪１":    "hair1_L",
	"左髪２":    "hair2_L",
	"左髪３":    "hair3_L",
	"左髪４":    "hair4_L",
	"左髪５":    "hair5_L",
	"左髪６":    "hair6_L",
	"左肩":     "shoulder_L",
	"左腕":     "arm_L",
	"左腕捩":    "arm twist_L",
	"左ひじ":    "elbow_L",
	"左手捩":    "wrist twist_L",
	"左手首":    "wrist_L",
	"左袖":     "sleeve_L",
	"左親指１":   "thumb1_L",
	"左親指２":   "thumb2_L",
	"左人指１":   "fore1_L",
	"左人指２":   "fore2_L",
	"左人指３":   "fore3_L",
	"左中指１":   "middle1_L",
	"左中指２":   "middle2_L",
	"左中指３":   "middle3_L",
	"左薬指１":   "third1_L",
	"左薬指２":   "third2_L",
	"左薬指３":   "third3_L",
	"左小指１":   "little1_L",
	"左小指２":   "little2_L",
	"左小指３":   "little3_L",
	"左ｽｶｰﾄ前": "front skirt_L",
	"左ｽｶｰﾄ後": "back skirt_L",
	"左足":     "leg_L",
	"左ひざ":    "knee_L",
	"左足首":    "ankle_L",
	"右髪１":    "hair1_R",
	"右髪２":    "hair2_R",
	"右髪３":    "hair3_R",
	"右髪４":    "hair4_R",
	"右髪５":    "hair5_R",
	"右髪６":    "hair6_R",
	"右肩":     "shoulder_R",
	"右腕":     "arm_R",
	"右腕捩":    "arm twist_R",
	"右ひじ":    "elbow_R",
	"右手捩":    "wrist twist_R",
	"右手首":    "wrist_R",
	"右袖":     "sleeve_R",
	"右親指１":   "thumb1_R",
	"右親指２":   "thumb2_R",
	"右人指１":   "fore1_R",
	"右人指２":   "fore2_R",
	"右人指３":   "fore3_R",
	"右中指１":   "middle1_R",
	"右中指２":   "middle2_R",
	"右中指３":   "middle3_R",
	"右薬指１":   "third1_R",
	"右薬指２":   "third2_R",
	"右薬指３":   "third3_R",
	"右小指１":   "little1_R",
	"右小指２":   "little2_R",
	"右小指３":   "little3_R",
	"右ｽｶｰﾄ前": "front skirt_R",
	"右ｽｶｰﾄ後": "back skirt_R",
	"右足":     "leg_R",
	"右ひざ":    "knee_R",
	"右足首":    "ankle_R",
	"両目":     "eyes",
	"前髪１":    "front hair1",
	"前髪２":    "front hair2",
	"前髪３":    "front hair3",
	"左目光":    "eyelight_L",
	"右目光":    "eyelight_R",
	"ﾈｸﾀｲ４":  "necktie4",
	"左髪７":    "hair7_L",
	"右髪７":    "hair7_R",
	"左つま先":   "toe_L",
	"右つま先":   "toe_R",
	"ﾈｸﾀｲＩＫ": "necktie IK",
	"左髪ＩＫ":   "hair IK_L",
	"右髪ＩＫ":   "hair IK_R",
	"左足ＩＫ":   "leg IK_L",
	"右足ＩＫ":   "leg IK_R",
	"左つま先ＩＫ": "toe IK_L",
	"右つま先ＩＫ": "toe IK_R",
}

// 标准Morph(表情)动画名称的日文英文对应表
var MorphNamesTable = map[string]string{
	"真面目":    "serious",
	"困る":     "sadness",
	"にこり":    "cheerful",
	"怒り":     "anger",
	"上":      "go up",
	"下":      "go down",
	"まばたき":   "blink",
	"笑い":     "smile",
	"ウィンク":   "wink",
	"ウィンク２":  "wink2",
	"ウィンク右":  "wink_R",
	"ｳｨﾝｸ２右": "wink2_R",
	"はぅ":     "close><",
	"なごみ":    "calm",
	"びっくり":   "surprise",
	"じと目":    "doubt",
	"なぬ！":    "confuse",
	"瞳小":     "pupil",
	"あ":      "a",
	"い":      "i",
	"う":      "u",
	"お":      "o",
	"▲":      "triangle",
	"∧":      "regret",
	"ω":      "omega",
	"ω□":     "omegabox",
	"はんっ！":   "fool",
	"ぺろっ":    "tongue",
	"えー":     "e-",
	"にやり":    "grin",
}
